version: '3'

services:
  app:
    build: .
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: python run.py